### ISSUE TITLE
jpeg->jpg; resize render

### ISSUE THREAD

**Issue by mcguirepatr** [niallmcc/simpledl#1]
Hi Niall
This is great! I trained the deep-learning neural net for Cats & Dogs with your code, and applied it with success to a new set of dogs and cats images. And it worked pretty well!

I had to modify the 'trunk/gui/scorer.py' code as follows to get it to work. Three changes in all. I changed 'jpeg' to 'jpg' and I resized the render image, in order to get it to fit on the laptop screen in the Tk Window. Can you incorporate these suggested changes into your code somehow?

```
self.filename = filedialog.askopenfilename(initialdir=".", title="Select file",
                                                        filetypes=(("jpg files", "*.jpg"), ("all files", "*.*")))
load = Image.open(self.filename)
load2  = load.resize((300,300), Image.ANTIALIAS)
render = ImageTk.PhotoImage(load2)
```

Thanks!
Patrick McGuire

**Comment by niallmcc** [comment]
Cool!  Thanks Patrick for this patch, I will get this change done!
Best,
Niall
